# Short Exercises - Part III - Chapter 07

### Median and Mode of an ___*array*___

In [197]:
### implement mode and median functions for 1 and 2 dimensional narrays

In [128]:
import numpy as np

In [129]:
arr = np.random.randint(1, 100, 20)
arr

array([66, 43, 13, 92, 69, 91, 70, 92, 23, 98, 95,  1, 49, 12, 11, 26,  7,
       12,  4, 18])

In [132]:
import statistics

In [172]:
def np_median(seq, axis=0):
    '''Calculates the median of a numpy array'''
    if axis == 1:
        seq = seq.T
    
    seq = sorted(seq.flatten())
    if len(seq) % 2 == 0: # if length is even
        return (seq[len(seq) // 2] + seq[(len(seq) // 2) - 1]) / 2
    
    return (seq[len(seq) // 2])


In [173]:
np_median(arr)

34.5

In [198]:
statistics.median(arr)

34.5

In [199]:
from operator import itemgetter

In [200]:
def np_mode(seq, axis=0):
    '''Calculates the mode of a numpy array'''
    if axis == 1:
        seq = seq.T
        
    values, frequencies = np.unique(seq, return_counts=True)
    head, *tail = list(reversed(sorted(list(zip(values, frequencies)), key=itemgetter(1))))
    return head[0]

In [201]:
statistics.mode(arr)

92

In [202]:
np_mode(arr)

92

In [203]:
### Multidimensional narrays

In [204]:
numbers = np.random.randint(1, 101, 25).reshape(5, 5)
numbers

array([[ 38,  36,  18,   5,   3],
       [ 49,  74,  78,  71,  21],
       [ 94,   8,  21,  87,  97],
       [ 23,  14,  50,  99,  88],
       [100,  62,  75,  65,  54]])

In [205]:
numbers.T

array([[ 38,  49,  94,  23, 100],
       [ 36,  74,   8,  14,  62],
       [ 18,  78,  21,  50,  75],
       [  5,  71,  87,  99,  65],
       [  3,  21,  97,  88,  54]])

In [206]:
np_median(numbers)

54

In [207]:
statistics.median(numbers.flatten())

54