# Linear Systems

In [1]:
import numpy as np

In [2]:
M = np.array([[1.,4,3,1],[2.,5.,4.,4.],[1,-3,-2,5]])
M

array([[ 1.,  4.,  3.,  1.],
       [ 2.,  5.,  4.,  4.],
       [ 1., -3., -2.,  5.]])

In [3]:
M[1,:] = 2*M[0,:] - M[1,:]
M

array([[ 1.,  4.,  3.,  1.],
       [ 0.,  3.,  2., -2.],
       [ 1., -3., -2.,  5.]])

In [4]:
M[2,:] = 1*M[0,:] - M[2,:]
M

array([[ 1.,  4.,  3.,  1.],
       [ 0.,  3.,  2., -2.],
       [ 0.,  7.,  5., -4.]])

In [5]:
M[1,:] = (1/3)*M[1,:]
M

array([[ 1.        ,  4.        ,  3.        ,  1.        ],
       [ 0.        ,  1.        ,  0.66666667, -0.66666667],
       [ 0.        ,  7.        ,  5.        , -4.        ]])

In [6]:
M[0,:] = -4*M[1,:] + M[0,]
M

array([[ 1.        ,  0.        ,  0.33333333,  3.66666667],
       [ 0.        ,  1.        ,  0.66666667, -0.66666667],
       [ 0.        ,  7.        ,  5.        , -4.        ]])

In [7]:
M[2,:] = -7*M[1,:] + M[2,:]
M

array([[ 1.        ,  0.        ,  0.33333333,  3.66666667],
       [ 0.        ,  1.        ,  0.66666667, -0.66666667],
       [ 0.        ,  0.        ,  0.33333333,  0.66666667]])

In [8]:
M[2,:] = 3*M[2,:]
M

array([[ 1.        ,  0.        ,  0.33333333,  3.66666667],
       [ 0.        ,  1.        ,  0.66666667, -0.66666667],
       [ 0.        ,  0.        ,  1.        ,  2.        ]])

In [9]:
M[0,:] = (-0.33333333*M[2,:]) + M[0,:]
M

array([[ 1.00000000e+00,  0.00000000e+00,  3.33333289e-09,
         3.00000001e+00],
       [ 0.00000000e+00,  1.00000000e+00,  6.66666667e-01,
        -6.66666667e-01],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.00000000e+00]])

In [10]:
M[1,:] = (-0.66666667)*M[2,:] + M[1,:]
M # x1 = 3, x2 = -2, x3 = 2

array([[ 1.00000000e+00,  0.00000000e+00,  3.33333289e-09,
         3.00000001e+00],
       [ 0.00000000e+00,  1.00000000e+00, -3.33333461e-09,
        -2.00000001e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.00000000e+00]])

In [11]:
np.round(M)

array([[ 1.,  0.,  0.,  3.],
       [ 0.,  1., -0., -2.],
       [ 0.,  0.,  1.,  2.]])