# Determinants

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,4], [5,3,-1], [7,2,0]])
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [6]:
det_A = np.linalg.det(A)
det_A

-56.00000000000002

In [7]:
B = np.array([[1,2,4,5,6,7], [5,3,-1,5,1,2], [7,2,0,1,4,9]])
B # can't calculate determinant. it must be a squared matrix

array([[ 1,  2,  4,  5,  6,  7],
       [ 5,  3, -1,  5,  1,  2],
       [ 7,  2,  0,  1,  4,  9]])

In [15]:
det_B = np.linalg.det(B) # error. Not a squared matrix. B.shape = 3x6

LinAlgError: Last 2 dimensions of the array must be square

In [9]:
C = np.array([[1,2,4,5,6,7], [5,3,-1,5,1,2], [7,2,0,1,4,9],
              [1,2,1,5,6,5], [-7,2,4,-1,6,6], [0,2,5,5,9,7]])
C.shape

(6, 6)

In [16]:
# calculate the determinant of C (6,6)
det_C = np.linalg.det(C)
det_C

8184.000000000006

### Properties of Determinants

In [17]:
A = np.array([[1,2,4],
              [5,3,-1],
              [7,2,0]]) # 3x3 squared matrix

Az = np.zeros((3,3)) # null matrix

In [18]:
A

array([[ 1,  2,  4],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [19]:
Az

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- 1. The determinant of null matrix is zero

In [22]:
det_Az = np.linalg.det(Az)
det_Az

0.0

- 2. The determinant of A = Determinant of A.T

In [23]:
np.linalg.det(A) == np.linalg.det(A.T)

True

- 3. If B = k*A[0,:], det(B) = k*det(A)

In [25]:
k = 3
F = A.copy()
F[0,:] = k*F[0,:]
F

array([[ 3,  6, 12],
       [ 5,  3, -1],
       [ 7,  2,  0]])

In [33]:
np.linalg.det(A).round() * k == np.linalg.det(F).round()

True

- 4. Swaping two rows negates the det signal

In [34]:
row1 = A[0,:]
row2 = A[1,:]
row3 = A[2,:]

In [36]:
G = np.array([row2, row1, row3])
G

array([[ 5,  3, -1],
       [ 1,  2,  4],
       [ 7,  2,  0]])

In [38]:
np.linalg.det(A) # negative

-56.00000000000002

In [39]:
np.linalg.det(G) # positive

56.00000000000002

In [40]:
np.linalg.det(A) == -(np.linalg.det(G))

True

- 5. Matrix with two equal rows -> determinant = 0

In [41]:
H = np.array([row1, row1, row3])
H

array([[1, 2, 4],
       [1, 2, 4],
       [7, 2, 0]])

In [42]:
np.linalg.det(H) == 0

True

- 6. Det(A+B) != det(A) + det(B)

In [49]:
B = np.array([[0,5,4], 
              [8,2,1], 
              [9,2,3]])

det_B = np.linalg.det(B)

In [50]:
np.linalg.det(A+B) != det_A + det_B

True

In [51]:
np.array_equal(np.linalg.det(A+B), det_A + det_B)

False

- 7. Determinant of the dot product == product of the determinants

In [54]:
np.linalg.det(A.dot(B)).round() == (det_A * det_B).round()

True