# Inverse Matrix

In [2]:
import numpy as np
from numpy.linalg import det, inv

In [3]:
A = np.array([[1,-7,2],
              [4,2,7],
              [1,4,-1]])
B = np.array([[1,1,2],
              [1,1,2],
              [3,-1,-1]])

In [4]:
A

array([[ 1, -7,  2],
       [ 4,  2,  7],
       [ 1,  4, -1]])

In [5]:
B

array([[ 1,  1,  2],
       [ 1,  1,  2],
       [ 3, -1, -1]])

In [6]:
# check if the inverse matrix exists. det(A) != 0
det(A) != 0

True

In [7]:
# get the inverse matrix of A
inv_A = inv(A)
inv_A

array([[ 0.37974684, -0.01265823,  0.67088608],
       [-0.13924051,  0.03797468, -0.01265823],
       [-0.17721519,  0.13924051, -0.37974684]])

In [11]:
inv_A.dot(A).round()

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
# check if B has an inverse matrix
det(B)

0.0

In [13]:
# since det(B) == 0, B has not inverse matrix

### Properties of Inverse Matrix

In [14]:
# those matrices do not represent general cases
C = np.array([[1,-2,3],
              [4,6,1],
              [0,2,1]])

D = np.array([[0,2,5],
              [1,3,1],
              [0,1,-3]])

In [15]:
C

array([[ 1, -2,  3],
       [ 4,  6,  1],
       [ 0,  2,  1]])

In [16]:
D

array([[ 0,  2,  5],
       [ 1,  3,  1],
       [ 0,  1, -3]])

- 1. if inv(A) exists then inv(inv(A)) also does


In [25]:
inv(D).round()

array([[-1.,  1., -1.],
       [ 0.,  0.,  0.],
       [ 0., -0., -0.]])

In [27]:
inv(inv(D)).round() == D

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- 2. inv(A\*B) = inv(B)\*inv(A)

In [28]:
inv(C.dot(D)).round() == inv(C).dot(inv(D)).round()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- 3. inv(A.T) = inv(A).T

In [31]:
inv(C.T).round() == inv(C).T.round()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])