# Matrices

In [1]:
import numpy as np

In [2]:
# Matrix
a = np.array([[2,-1], [0,4]])
a

array([[ 2, -1],
       [ 0,  4]])

In [3]:
b = np.array([[1, 0, 4],
              [4, -3, 2]])
b

array([[ 1,  0,  4],
       [ 4, -3,  2]])

### Matrix Function

In [4]:
c = np.matrix('1 2; 3 4')
c

matrix([[1, 2],
        [3, 4]])

In [5]:
d = np.matrix([[2, -1],
               [0, 4]])
d

matrix([[ 2, -1],
        [ 0,  4]])

In [6]:
type(d)

numpy.matrix

### Types of Matrices

In [7]:
# Row Matrix
r_mt = np.array([[3, 4, 5]])
r_mt

array([[3, 4, 5]])

In [8]:
# Column Matrix
c_mt = np.matrix([[1], [2], [3]])
c_mt

matrix([[1],
        [2],
        [3]])

In [9]:
# Null Matrix
n_zeros = np.zeros((2,2))
n_zeros

array([[0., 0.],
       [0., 0.]])

In [10]:
n2_zeros = np.zeros((5,5))
n2_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Diagonal Matrix
d_mt = np.diag([1,3,5,6,7])
d_mt

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

In [12]:
# Identity Matrix
id_mt = np.eye(4,4)
id_mt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matrix Transpose

In [13]:
s = np.array([[1,4,3], [4,2,5], [3,5,0]]) # symmetric matrix
a = np.array([[1,2,3,6], [9,7,4,6]])
b = np.array([[8, 5, 3, 3], [1,0,1,8]])

In [14]:
s

array([[1, 4, 3],
       [4, 2, 5],
       [3, 5, 0]])

In [15]:
# check if s is symetric using its transpose
np.array_equal(s,s.T)

True

In [16]:
# tranpose a
a

array([[1, 2, 3, 6],
       [9, 7, 4, 6]])

In [17]:
a_t = np.transpose(a)
a_t

array([[1, 9],
       [2, 7],
       [3, 4],
       [6, 6]])

In [18]:
a_t.T # transpose of transpose is the original matrix

array([[1, 2, 3, 6],
       [9, 7, 4, 6]])

#### Transpose Matrix Properties

In [19]:
# simmetric equality
# s = s.T

np.array_equal(s,s.T)

True

In [20]:
# transpose of transpose is the original matrix
np.array_equal(s.T.T, s)

True

In [21]:
# the transposed sum is equal to the sum of transposed
np.array_equal((a+b).T, a.T + b.T)

True

In [22]:
# (scalar * matrix)Transpose = scalar * (matrix Transpose)
k = 7
np.array_equal((k*a).T, k*a.T)

True

### Slicing Matrices

In [23]:
a = np.array([[2,4,6], [4,7,1], [9,3,8]])
a

array([[2, 4, 6],
       [4, 7, 1],
       [9, 3, 8]])

In [24]:
a.shape

(3, 3)

In [25]:
# get the second row
a[1,:]

array([4, 7, 1])

In [26]:
# get a2,2
a[1,1]

7

In [27]:
# get a3,3
a[2,2]

8

In [28]:
b = a

In [29]:
# set b2,3 = 77
b[1,2] = 77

In [30]:
b

array([[ 2,  4,  6],
       [ 4,  7, 77],
       [ 9,  3,  8]])

In [31]:
# note that b is just a pointer to a. A also changes. 
# to make a copy we need to use the copy function
a # it also has b2,3 == 77

array([[ 2,  4,  6],
       [ 4,  7, 77],
       [ 9,  3,  8]])

In [32]:
c = b.copy()
c

array([[ 2,  4,  6],
       [ 4,  7, 77],
       [ 9,  3,  8]])

In [33]:
# changing c won't change b in this case
c[2,0] = 123
c

array([[  2,   4,   6],
       [  4,   7,  77],
       [123,   3,   8]])

In [34]:
b # b2,1 is not 123

array([[ 2,  4,  6],
       [ 4,  7, 77],
       [ 9,  3,  8]])

In [35]:
f = c[:, 1] # save column 1 in f
f

array([4, 7, 3])

In [36]:
A = np.array([[2,3,7,1], [8,6,9,3], [6,9,3,2], [4,3,7,5]])

In [37]:
A.shape

(4, 4)

In [38]:
A[2,1:4]

array([9, 3, 2])

In [39]:
A[3,0:3]

array([4, 3, 7])

In [40]:
A

array([[2, 3, 7, 1],
       [8, 6, 9, 3],
       [6, 9, 3, 2],
       [4, 3, 7, 5]])

In [41]:
A[1:4,2]

array([9, 3, 7])

### Operations with Matrices

In [42]:
# create matrices
J = np.array([[2,4,6], [1,2,7], [3,2,9]])
K = np.array([[-1,4,5], [6,3,1]])
L = np.array([[0,4,3], [1,-3,1], [3,1,2]])

In [43]:
print(f'J:\n{J}\n{J.shape}\n')
print(f'K:\n{K}\n{K.shape}\n')
print(f'L:\n{L}\n{L.shape}\n')

J:
[[2 4 6]
 [1 2 7]
 [3 2 9]]
(3, 3)

K:
[[-1  4  5]
 [ 6  3  1]]
(2, 3)

L:
[[ 0  4  3]
 [ 1 -3  1]
 [ 3  1  2]]
(3, 3)



#### Sum

In [44]:
J + K # it wont work because they do not have the same amount of rows and columns

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [45]:
# Sum lines
J[0,:] + K[0,:]

array([ 1,  8, 11])

In [46]:
# Sum Matrices
J + L

array([[ 2,  8,  9],
       [ 2, -1,  8],
       [ 6,  3, 11]])

In [47]:
# Subtract Matrices
J - L

array([[2, 0, 3],
       [0, 5, 6],
       [0, 1, 7]])

In [52]:
# Multiplication Matrices
F = np.dot(J,L)
F

array([[22,  2, 22],
       [23,  5, 19],
       [29, 15, 29]])

In [53]:
# Division
J / L

<ipython-input-53-2e6b16971391>:2: RuntimeWarning: divide by zero encountered in true_divide
  J / L


array([[        inf,  1.        ,  2.        ],
       [ 1.        , -0.66666667,  7.        ],
       [ 1.        ,  2.        ,  4.5       ]])

In [54]:
# scalar multiplication
n = 2
n * J

array([[ 4,  8, 12],
       [ 2,  4, 14],
       [ 6,  4, 18]])

In [55]:
# validating multiplication
f11 = F[0,0]
f11_ = J[0,:].dot(L[:,0])
f11 == f11_


True

In [56]:
f12 = F[0,1]
f12_ = J[0,:].dot(L[:,1])
f12 == f12_

True