# iPython Sessions - Part II - Chapter 07

In [16]:
import numpy as np 

In [17]:
numbers = np.arange(1, 6)

In [18]:
numbers

array([1, 2, 3, 4, 5])

In [19]:
# multiply all elements by 2
numbers * 2

array([ 2,  4,  6,  8, 10])

In [20]:
# cube all elements
numbers ** 3

array([  1,   8,  27,  64, 125])

In [21]:
numbers  # it remains unchanged

array([1, 2, 3, 4, 5])

In [22]:
numbers += 10 # modify every element in the left operand

In [23]:
numbers

array([11, 12, 13, 14, 15])

### Aritmetic operations

In [29]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [30]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [26]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

### Comparring arrays
#### Comparisons are performed element-wise

In [38]:
numbers

array([11, 12, 13, 14, 15])

In [39]:
numbers >= 13

array([False, False,  True,  True,  True])

In [40]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [41]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [42]:
numbers == numbers2

array([False, False, False, False, False])

In [43]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [44]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

### NumPy Calculation Methods

In [51]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                  [94, 77, 90], [100, 81, 82]])

In [52]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [54]:
# sum all elements
grades.sum()

1054

In [55]:
# min of all elements
grades.min()

70

In [56]:
# max of all elements
grades.max()

100

In [58]:
# std deviation
grades.std()

8.792357792739987

In [59]:
# variance
grades.var()

77.30555555555556

### Calculation by row or column

In [63]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [61]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [64]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [65]:
grades2 = np.random.randint(60, 101, 12).reshape(3, 4)

In [66]:
grades2

array([[83, 83, 94, 78],
       [85, 89, 61, 68],
       [93, 60, 63, 95]])

In [70]:
# mean
grades2.mean()

79.33333333333333

In [71]:
# average by column
grades2.mean(axis=0)

array([87.        , 77.33333333, 72.66666667, 80.33333333])

In [72]:
# average by row
grades2.mean(axis=1)

array([84.5 , 75.75, 77.75])

In [75]:
numbers3 = np.arange(1, 6)

In [77]:
numbers3 ** 3

array([  1,   8,  27,  64, 125])

In [80]:
np.power(numbers3, 3)

array([  1,   8,  27,  64, 125])