# iPython Sessions - Part IV - Chapter 07

In [66]:
import numpy as np

In [67]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [68]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [69]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [70]:
grades # reshaping does not modify the original array

array([[ 87,  96,  70],
       [100,  87,  90]])

In [71]:
grades.resize(1, 6) # resizing changes the original array

In [72]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [73]:
# flatten vs ravel
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [74]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [75]:
flattened = grades.flatten() # deep copy

In [76]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [77]:
grades # remains unchanged

array([[ 87,  96,  70],
       [100,  87,  90]])

In [78]:
# using ravel
raveled = grades.ravel()

In [79]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [80]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [81]:
raveled[0] = 100 # it will change the value in grades as well. shallow copy

In [82]:
raveled

array([100,  96,  70, 100,  87,  90])

In [83]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [65]:
### Transposing Rows and Columns

In [84]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [85]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [86]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Horizontal and Vertical Stacking

In [88]:
grades2 = np.array([[94, 77, 99], [100, 81, 82]])

In [89]:
grades2

array([[ 94,  77,  99],
       [100,  81,  82]])

In [90]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  99],
       [100,  87,  90, 100,  81,  82]])

In [91]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  99],
       [100,  81,  82]])

### Self Check

In [98]:
numbers = np.arange(1, 7).reshape(2, 3)

In [99]:
numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
a = np.hstack((numbers, numbers))

In [110]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [114]:
a = np.vstack((a, a))

In [115]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [116]:
b = np.vstack((np.hstack((numbers, numbers)), np.hstack((numbers, numbers))))

In [117]:
b

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])