# Short Exercises - Part I - Chapter 07

In [1]:
import numpy as np 
import pandas as pd

### Filling arrays

In [2]:
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [3]:
zeros = np.zeros((3, 3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
sevens = np.full((2, 5), 7)
sevens

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

### Broadcasting

In [5]:
numbers = np.arange(0, 4).reshape(2, 2)
numbers

array([[0, 1],
       [2, 3]])

In [6]:
# cube
numbers ** 3

array([[ 0,  1],
       [ 8, 27]])

In [7]:
numbers + 7

array([[ 7,  8],
       [ 9, 10]])

In [8]:
numbers * 2

array([[0, 2],
       [4, 6]])

### Element-Wise __array__ Multiplication

In [9]:
a1 = np.arange(2, 20, 2).reshape(3, 3)
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
a2 = np.arange(9, 0, -1).reshape(3, 3)
a2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [11]:
a1 * a2

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

### ___array___ from List of Lists

In [12]:
np.array([[2, 3, 5, 7, 11], [13, 17, 19, 23, 29]])

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

### Flattening ___array___ with ___flatten___ vs ___ravel___

In [13]:
original = np.array([2 ** x for x in range(0, 6)]).reshape(2, 3)

In [14]:
flattened = original.flatten()
flattened

array([ 1,  2,  4,  8, 16, 32])

In [15]:
original

array([[ 1,  2,  4],
       [ 8, 16, 32]])

In [17]:
raveled = original.ravel()
raveled

array([ 1,  2,  4,  8, 16, 32])

In [18]:
raveled[0] = 100
original

array([[100,   2,   4],
       [  8,  16,  32]])

### ___array___ Method astype

In [19]:
a3 = np.linspace(1.1, 6.6, 6).reshape(2, 3)
a3 = a3.astype(int)
a3

array([[1, 2, 3],
       [4, 5, 6]])

### (Challenge): Reimplement NumPy array Output

In [20]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
import math

def indentation(n):
    '''Returns the number of spaces based on n's magnitude'''
    return math.floor(math.log10(n))+1

In [22]:
def np_print(twodim):
    '''Reimplements NumPy's array output'''
    indent = indentation(twodim.max())
    str_rep = 'array(['
    for idx, row in enumerate(twodim):
        str_row = '['
        for cdx, column in enumerate(row):
            if cdx == len(row) - 1:  # last column
                str_row += f'{column:>{indent}}'
            else:
                str_row += f'{column:>{indent}}, '
    
        if idx == len(twodim) - 1:  # last row
            str_row += ']])'
        else:
            str_row += f'],\n' + ' ' * 7
        
        str_rep += str_row

    return print(str_rep)

In [23]:
a4 = np.linspace(1.1, 89.6, 20).reshape(5, 4)
a4 = a4.astype(int)
a4

array([[ 1,  5, 10, 15],
       [19, 24, 29, 33],
       [38, 43, 47, 52],
       [56, 61, 66, 70],
       [75, 80, 84, 89]])

In [25]:
np_print(a4)

array([[ 1,  5, 10, 15],
       [19, 24, 29, 33],
       [38, 43, 47, 52],
       [56, 61, 66, 70],
       [75, 80, 84, 89]])


In [26]:
np_print(a4) == print(a4)

array([[ 1,  5, 10, 15],
       [19, 24, 29, 33],
       [38, 43, 47, 52],
       [56, 61, 66, 70],
       [75, 80, 84, 89]])
[[ 1  5 10 15]
 [19 24 29 33]
 [38 43 47 52]
 [56 61 66 70]
 [75 80 84 89]]


True