# iPython Sessions - Part III - Chapter 07

In [2]:
import numpy as np

In [3]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [4]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

### indexing two dimensional arrays

In [5]:

grades[0, 1] # row 0, column 1

96

In [6]:
grades[1] # row 1

array([100,  87,  90])

### slicing two dimensional arrays

In [8]:
grades[0:2] # row 0 - 1

array([[ 87,  96,  70],
       [100,  87,  90]])

In [9]:
grades[1:3] # row 1 - 2

array([[100,  87,  90],
       [ 94,  77,  90]])

In [12]:
grades[:, 0] # all rows - first column

array([ 87, 100,  94, 100])

In [13]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [14]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [15]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

### Self Check

In [17]:
numbers = np.arange(1, 16).reshape(3, 5)

In [35]:
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
# select the second row
numbers[1]

array([ 6,  7,  8,  9, 10])

In [37]:
# select the first and third rows
numbers[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [38]:
numbers[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

### Views: Shallow Copies

In [39]:
values = np.arange(1, 6)

In [40]:
values

array([1, 2, 3, 4, 5])

In [41]:
values2 = values.view()

In [42]:
values2

array([1, 2, 3, 4, 5])

In [43]:
id(values)

140552151552528

In [44]:
id(values2)

140552154134528

In [45]:
values[1] *= 10

In [46]:
values2

array([ 1, 20,  3,  4,  5])

In [47]:
values

array([ 1, 20,  3,  4,  5])

In [52]:
values2[1] /= 10 # changing values2 also changes value

In [53]:
values2

array([1, 0, 3, 4, 5])

In [54]:
values

array([1, 0, 3, 4, 5])

### Slice Views

In [58]:
numbers = np.arange(1, 6)

In [59]:
numbers2 = numbers[0:3]

In [60]:
numbers2

array([1, 2, 3])

In [61]:
id(numbers)

140552164564064

In [62]:
id(numbers2)

140552165770624

In [63]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [64]:
numbers[1] *= 20

In [65]:
numbers

array([ 1, 40,  3,  4,  5])

In [66]:
numbers2

array([ 1, 40,  3])

### Deep Copies

In [69]:
numbers = np.arange(1, 6)

In [70]:
numbers

array([1, 2, 3, 4, 5])

In [71]:
numbers2 = numbers.copy()

In [72]:
numbers2

array([1, 2, 3, 4, 5])

In [73]:
id(numbers)

140552157058592

In [74]:
id(numbers2)

140552157059712

In [77]:
# changing numbers won't change number2
numbers[1] *= 10

In [78]:
numbers

array([ 1, 20,  3,  4,  5])

In [81]:
numbers2 # deep copy. unchanged

array([1, 2, 3, 4, 5])