# iPython Sessions - Chapter 07

In [29]:
import numpy as np

In [30]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
integers = np.array([[x for x in range(2, 11) if x % 2 == 0], [x for x in range(1, 10) if x % 2 != 0]])


In [36]:
integers

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [37]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [38]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [39]:
integers.dtype

dtype('int64')

In [40]:
floats.dtype

dtype('float64')

In [41]:
# shape of the narray
integers.shape

(2, 5)

In [42]:
floats.shape

(5,)

In [44]:
# total number of elements
# if multidimensional (x, y), size = x * y
integers.size

10

In [45]:
# storage used by item 
integers.itemsize

8

In [46]:
# fill up array with 0s
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
# fill up array with 1s
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [48]:
# fill up array with any number
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

### Creating arrays using arange

In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [52]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [54]:
# linspace divides evenly the range specified
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshaping narrays

In [55]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [58]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [59]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

### List vs Array Performance

In [64]:
import random

In [65]:
%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

4.11 s ± 143 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [66]:
import numpy as np

In [67]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

60.7 ms ± 93.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [68]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

749 ms ± 6.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

8.04 s ± 81.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [70]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

64.9 ms ± 5.06 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [71]:
%load?

Docstring:
Load code into the current frontend.

Usage:
  %load [options] source

  where source can be a filename, URL, input history range, macro, or
  element in the user namespace

Options:

  -r <lines>: Specify lines or ranges of lines to load from the source.
  Ranges could be specified as x-y (x..y) or in python-style x:y 
  (x..(y-1)). Both limits x and y can be left blank (meaning the 
  beginning and end of the file, respectively).

  -s <symbols>: Specify function or classes to load from python source. 

  -y : Don't ask confirmation for loading source above 200 000 characters.

  -n : Include the user's namespace when searching for source code.

This magic command can either take a local filename, a URL, an history
range (see %history) or a macro as argument, it will prompt for
confirmation before loading source with more than 200 000 characters, unless
-y flag is passed or if the frontend does not support raw_input::

%load myscript.py
%load 7-27
%load myMacro
%load http:

### Compare execution time of sum list and narray sum

In [75]:
%timeit sum([x for x in range(10_000_000)])

613 ms ± 6.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [76]:
%timeit np.arange(10_000_000).sum()

19.9 ms ± 852 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
