# Short Exercises - Part II - Chapter 07

In [130]:
import numpy as np 
import pandas as pd

### Indexing and slicing ___arrays___

In [131]:
values = np.arange(1, 16).reshape(3, 5)
values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [132]:
values[1]

array([ 6,  7,  8,  9, 10])

In [133]:
values[:, 4]

array([ 5, 10, 15])

In [134]:
values[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [135]:
values[:, [2, 4]]

array([[ 3,  5],
       [ 8, 10],
       [13, 15]])

In [136]:
values[0, 4]

5

In [137]:
values[0: 2, [0, 2, 4]]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

### Horizontal and Vertical Stacking

In [138]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

In [139]:
# stack array2 on top of array1 using vertical stacking
array3 = np.vstack((array1, array2))
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [140]:
# stack array2 to the right of array1 using horizontal stacking
array4 = np.hstack((array1, array2))
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [141]:
array5 = np.vstack((array4, array4))
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [142]:
array6 = np.hstack((array3, array3))
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [143]:
array1

array([[0, 1],
       [2, 3]])

In [144]:
array2

array([[4, 5],
       [6, 7]])

### Concatenate function

In [145]:
# Using concatenate, put array1 on top of array2 to create a 4x2
a1 = np.concatenate((array1, array2), axis=0)
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [146]:
a1 == array3

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [147]:
# put array2 to the right of array1 to create a 2x4
a2 = np.concatenate((array1, array2), axis=1)
a2

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [148]:
a2 == array4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [149]:
# stack two copies of a2 to create a 4x4
a3 = np.concatenate((a2, a2), axis=0)
a3

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [150]:
a3 == array5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [151]:
# concatenate two copies of a1 to make a 4x4 array
a4 = np.concatenate((a1, a1), axis=1)
a4

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [152]:
a4 == array6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Tile Function

In [153]:
# Generate a pattern of dashes and asterisks


In [154]:
dash_ast = np.array(['*', '-'])
dash_ast

array(['*', '-'], dtype='<U1')

In [155]:
pattern = np.tile(dash_ast, (5, 5))
pattern

array([['*', '-', '*', '-', '*', '-', '*', '-', '*', '-'],
       ['*', '-', '*', '-', '*', '-', '*', '-', '*', '-'],
       ['*', '-', '*', '-', '*', '-', '*', '-', '*', '-'],
       ['*', '-', '*', '-', '*', '-', '*', '-', '*', '-'],
       ['*', '-', '*', '-', '*', '-', '*', '-', '*', '-']], dtype='<U1')

In [156]:
for line in pattern:
    print(' '.join(line))

* - * - * - * - * -
* - * - * - * - * -
* - * - * - * - * -
* - * - * - * - * -
* - * - * - * - * -


### bincount Function

In [157]:
# count ocurrences based on a 5x5 reshaped array

numbers = np.random.randint(1, 101, 25).reshape(5, 5)
numbers

array([[69, 55, 32, 71, 16],
       [79, 86, 90, 50, 98],
       [88, 36,  2, 47,  3],
       [33,  4, 91, 64, 26],
       [55,  3, 42, 95, 23]])

In [ ]:
# make the array the same shape as the bincount
numbers = numbers.flatten()
list(zip(np.arange(1, 101), np.bincount(numbers)))