# Short Exercises - Part II - Chapter 07

In [1]:
import numpy as np 
import pandas as pd

### Indexing and slicing ___arrays___

In [4]:
values = np.arange(1, 16).reshape(3, 5)
values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
values[1]

array([ 6,  7,  8,  9, 10])

In [9]:
values[:, 4]

array([ 5, 10, 15])

In [13]:
values[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
values[:, [2, 4]]

array([[ 3,  5],
       [ 8, 10],
       [13, 15]])

In [16]:
values[0, 4]

5

In [19]:
values[0: 2, [0, 2, 4]]

array([[ 1,  3,  5],
       [ 6,  8, 10]])